services:
  openplot-api:
    build:
      context: .
      dockerfile: OpenPlot.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AuthProvider__Provider: OpenPlot
      ConfigIT_ENABLED: "false"

  openplot-ingestor-gsf:
    build:
      context: .
      dockerfile: OpenPlot.Ingestor.Gsf/Dockerfile
