-- OpenPlot - schema ajustado para TimescaleDB
-- Script DDL limpo: cria schema, tipos, tabelas, constraints, indices, hypertable e grants.
-- Nao inclui dados, COPY, DROP nem CREATE DATABASE.
-- Recomendado executar em um banco ja criado, por exemplo: database openplot, schema openplot.
-- Requisito: a extensao TimescaleDB deve estar disponivel no servidor PostgreSQL.

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- -----------------------------------------------------------------------------
-- TimescaleDB
-- -----------------------------------------------------------------------------
-- Em Docker, utilize uma imagem com TimescaleDB instalado, por exemplo timescale/timescaledb.
-- Este comando precisa ser executado por usuario com permissao para criar extensoes.

CREATE EXTENSION IF NOT EXISTS timescaledb;

-- -----------------------------------------------------------------------------
-- Schema e role de leitura
-- -----------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS openplot;
SET search_path = openplot, public;

-- Role opcional para Grafana.
-- Por seguranca, a role e criada sem LOGIN. Caso o Grafana conecte diretamente,
-- defina LOGIN e PASSWORD em um script separado/seguro.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_roles
        WHERE rolname = 'grafana'
    ) THEN
        CREATE ROLE grafana;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA openplot TO grafana;

DO $$
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO grafana', current_database());
END
$$;

-- -----------------------------------------------------------------------------
-- Tipos controlados
-- -----------------------------------------------------------------------------
-- Observacao: mantidos os valores ja usados pelo projeto para reduzir impacto
-- na API/front. THD foi adicionado em qty_kind por aparecer como grandeza
-- analitica em agrupamentos anteriores.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'openplot'
          AND t.typname = 'qty_kind'
    ) THEN
        CREATE TYPE openplot.qty_kind AS ENUM (
            'Voltage',
            'Current',
            'Frequency',
            'Digital',
            'THD'
        );
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'openplot'
          AND t.typname = 'phase_kind'
    ) THEN
        CREATE TYPE openplot.phase_kind AS ENUM (
            'A',
            'B',
            'C',
            'None',
            'Digital'
        );
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'openplot'
          AND t.typname = 'comp_kind'
    ) THEN
        CREATE TYPE openplot.comp_kind AS ENUM (
            'MAG',
            'ANG',
            'FREQ',
            'DFREQ',
            'THD',
            'DIG'
        );
    END IF;
END
$$;

-- -----------------------------------------------------------------------------
-- Tabelas de metadados
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS openplot.pdc (
    pdc_id      integer GENERATED BY DEFAULT AS IDENTITY,
    name        text NOT NULL,
    kind        text NOT NULL,
    fps         integer NOT NULL,
    address     text NOT NULL,
    username    text,
    password    text,
    db_name     text,
    active      boolean NOT NULL DEFAULT true,

    CONSTRAINT pdc_pkey PRIMARY KEY (pdc_id),
    CONSTRAINT pdc_name_key UNIQUE (name),
    CONSTRAINT pdc_fps_check CHECK (fps > 0)
);

CREATE TABLE IF NOT EXISTS openplot.pmu (
    pmu_id      integer GENERATED BY DEFAULT AS IDENTITY,
    id_name     text NOT NULL,
    full_name   text,
    volt_level  integer,
    area        text,
    state       text,
    station     text,
    lat         double precision,
    lon         double precision,

    CONSTRAINT pmu_pkey PRIMARY KEY (pmu_id),
    CONSTRAINT pmu_id_name_key UNIQUE (id_name),
    CONSTRAINT pmu_lat_check CHECK (lat IS NULL OR (lat >= -90 AND lat <= 90)),
    CONSTRAINT pmu_lon_check CHECK (lon IS NULL OR (lon >= -180 AND lon <= 180))
);

CREATE TABLE IF NOT EXISTS openplot.pdc_pmu (
    pdc_pmu_id       integer GENERATED BY DEFAULT AS IDENTITY,
    pdc_id           integer NOT NULL,
    pmu_id           integer NOT NULL,
    pdc_local_id     text,
    kind             text,
    local_numeric_id integer,

    CONSTRAINT pdc_pmu_pkey PRIMARY KEY (pdc_pmu_id),
    CONSTRAINT pdc_pmu_pdc_id_pmu_id_key UNIQUE (pdc_id, pmu_id),
    CONSTRAINT pdc_pmu_pdc_id_fkey
        FOREIGN KEY (pdc_id)
        REFERENCES openplot.pdc (pdc_id)
        ON DELETE CASCADE,
    CONSTRAINT pdc_pmu_pmu_id_fkey
        FOREIGN KEY (pmu_id)
        REFERENCES openplot.pmu (pmu_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS openplot.signal (
    signal_id       integer GENERATED BY DEFAULT AS IDENTITY,
    pdc_pmu_id      integer NOT NULL,
    name            text NOT NULL,
    historian_point integer NOT NULL,
    quantity        openplot.qty_kind NOT NULL,
    phase           openplot.phase_kind NOT NULL DEFAULT 'None',
    component       openplot.comp_kind NOT NULL,

    CONSTRAINT signal_pkey PRIMARY KEY (signal_id),
    CONSTRAINT signal_pdc_pmu_id_fkey
        FOREIGN KEY (pdc_pmu_id)
        REFERENCES openplot.pdc_pmu (pdc_pmu_id)
        ON DELETE CASCADE,

    -- Necessaria para uso seguro de ON CONFLICT na importacao de XML/sinais.
    CONSTRAINT signal_pdc_pmu_name_phase_component_key
        UNIQUE (pdc_pmu_id, name, phase, component),

    -- Evita combinacoes sem sentido para digitais, mas ainda permite phase='Digital'
    -- por compatibilidade com dados/codigo existentes.
    CONSTRAINT signal_digital_consistency_check CHECK (
        (quantity = 'Digital' AND component = 'DIG')
        OR
        (quantity <> 'Digital' AND component <> 'DIG')
    )
);

CREATE TABLE IF NOT EXISTS openplot.signal_points (
    signal_id integer NOT NULL,
    pdc_id    integer NOT NULL,
    role      text NOT NULL,
    point_id  bigint NOT NULL,

    CONSTRAINT signal_points_pkey PRIMARY KEY (signal_id, role),
    CONSTRAINT signal_points_pdc_id_point_id_key UNIQUE (pdc_id, point_id),
    CONSTRAINT signal_points_signal_id_fkey
        FOREIGN KEY (signal_id)
        REFERENCES openplot.signal (signal_id)
        ON DELETE CASCADE,
    CONSTRAINT signal_points_pdc_id_fkey
        FOREIGN KEY (pdc_id)
        REFERENCES openplot.pdc (pdc_id)
        ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Buscas, caches, chunks e processamentos
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS openplot.search_runs (
    id           uuid NOT NULL,
    source       text NOT NULL,
    terminal_id  text,
    signals      jsonb NOT NULL,
    from_ts      timestamp with time zone NOT NULL,
    to_ts        timestamp with time zone NOT NULL,
    select_rate  integer NOT NULL DEFAULT 0,
    status       text NOT NULL,
    progress     integer NOT NULL DEFAULT 0,
    message      text,
    created_at   timestamp with time zone NOT NULL DEFAULT now(),
    pdc_id       integer,
    signal_count integer DEFAULT 0,
    pmu_count    integer DEFAULT 0,
    label        text,
    pmus         jsonb,
    pmus_ok      jsonb,
    username     text,
    shared       boolean NOT NULL DEFAULT false,
    is_visible   boolean NOT NULL DEFAULT true,
    deleted_at   timestamp with time zone,
    started_at   timestamp with time zone,
    finished_at  timestamp with time zone,

    CONSTRAINT search_runs_pkey PRIMARY KEY (id),
    CONSTRAINT search_runs_pdc_id_fkey
        FOREIGN KEY (pdc_id)
        REFERENCES openplot.pdc (pdc_id)
        ON DELETE SET NULL,
    CONSTRAINT search_runs_status_check CHECK (
        status IN ('queued', 'running', 'done', 'failed', 'canceled')
    ),
    CONSTRAINT search_runs_progress_check CHECK (progress >= 0 AND progress <= 100),
    CONSTRAINT search_runs_select_rate_check CHECK (select_rate >= 0),
    CONSTRAINT search_runs_signal_count_check CHECK (signal_count IS NULL OR signal_count >= 0),
    CONSTRAINT search_runs_pmu_count_check CHECK (pmu_count IS NULL OR pmu_count >= 0),
    CONSTRAINT search_runs_time_range_check CHECK (from_ts <= to_ts),
    CONSTRAINT search_runs_finished_after_started_check CHECK (
        started_at IS NULL
        OR finished_at IS NULL
        OR started_at <= finished_at
    )
);

CREATE TABLE IF NOT EXISTS openplot.analysis_cache (
    cache_id         uuid NOT NULL,
    job_id           uuid NOT NULL,
    payload          jsonb NOT NULL,
    last_accessed_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT analysis_cache_pkey PRIMARY KEY (cache_id),
    CONSTRAINT analysis_cache_job_id_fkey
        FOREIGN KEY (job_id)
        REFERENCES openplot.search_runs (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS openplot.ingest_chunks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    job_id      uuid NOT NULL,
    signal_id   integer NOT NULL,
    from_ts     timestamp with time zone NOT NULL,
    to_ts       timestamp with time zone NOT NULL,
    rowcount    integer NOT NULL,
    inserted_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT ingest_chunks_pkey PRIMARY KEY (id),
    CONSTRAINT ingest_chunks_job_id_fkey
        FOREIGN KEY (job_id)
        REFERENCES openplot.search_runs (id)
        ON DELETE CASCADE,
    CONSTRAINT ingest_chunks_signal_id_fkey
        FOREIGN KEY (signal_id)
        REFERENCES openplot.signal (signal_id)
        ON DELETE CASCADE,
    CONSTRAINT ingest_chunks_time_range_check CHECK (from_ts <= to_ts),
    CONSTRAINT ingest_chunks_rowcount_check CHECK (rowcount >= 0)
);

CREATE TABLE IF NOT EXISTS openplot.comtrade_runs (
    run_id      uuid NOT NULL,
    status      text NOT NULL DEFAULT 'queued',
    progress    integer NOT NULL DEFAULT 0,
    message     text,
    dir_path    text,
    file_name   text,
    size_bytes  bigint,
    sha256      text,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    started_at  timestamp with time zone,
    finished_at timestamp with time zone,
    created_by  text,
    error       text,

    CONSTRAINT comtrade_runs_pkey PRIMARY KEY (run_id),
    CONSTRAINT comtrade_runs_run_id_fkey
        FOREIGN KEY (run_id)
        REFERENCES openplot.search_runs (id)
        ON DELETE RESTRICT,
    CONSTRAINT comtrade_runs_status_check CHECK (
        status IN ('queued', 'running', 'done', 'failed', 'canceled')
    ),
    CONSTRAINT comtrade_runs_progress_check CHECK (progress >= 0 AND progress <= 100),
    CONSTRAINT comtrade_runs_size_bytes_check CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT comtrade_runs_finished_after_started_check CHECK (
        started_at IS NULL
        OR finished_at IS NULL
        OR started_at <= finished_at
    )
);

-- -----------------------------------------------------------------------------
-- Series temporais - TimescaleDB
-- -----------------------------------------------------------------------------
-- A tabela definitiva de series temporais passa a ser measurements_ht.
-- A tabela measurements NAO e criada como tabela fisica neste script.
-- Para compatibilidade com codigo legado, uma VIEW measurements e criada ao final
-- apontando para measurements_ht.
--
-- Observacao TimescaleDB:
-- Toda PRIMARY KEY/UNIQUE em hypertable precisa conter a coluna de particionamento
-- temporal. Por isso a PK inclui ts.

CREATE TABLE IF NOT EXISTS openplot.measurements_ht (
    ts          timestamp with time zone NOT NULL,
    pdc_pmu_id  integer NOT NULL,
    signal_id   integer NOT NULL,
    value       double precision NOT NULL,

    CONSTRAINT measurements_ht_pkey PRIMARY KEY (pdc_pmu_id, signal_id, ts),
    CONSTRAINT measurements_ht_pdc_pmu_id_fkey
        FOREIGN KEY (pdc_pmu_id)
        REFERENCES openplot.pdc_pmu (pdc_pmu_id)
        ON DELETE CASCADE,
    CONSTRAINT measurements_ht_signal_id_fkey
        FOREIGN KEY (signal_id)
        REFERENCES openplot.signal (signal_id)
        ON DELETE CASCADE
);

-- Converte a tabela fisica para hypertable.
-- chunk_time_interval = 1 hour foi escolhido por padrao conservador para dados
-- de sincrofasores em alta taxa. Ajuste para 6 hours ou 1 day se o volume for menor.
SELECT create_hypertable(
    'openplot.measurements_ht',
    'ts',
    chunk_time_interval => INTERVAL '1 hour',
    if_not_exists => TRUE,
    create_default_indexes => FALSE
);

COMMENT ON TABLE openplot.measurements_ht IS
'Tabela definitiva de series temporais do OpenPlot, armazenada como hypertable TimescaleDB particionada por ts.';

COMMENT ON COLUMN openplot.measurements_ht.ts IS 'Instante da amostra, em timestamptz.';
COMMENT ON COLUMN openplot.measurements_ht.pdc_pmu_id IS 'Referencia ao par PDC-PMU.';
COMMENT ON COLUMN openplot.measurements_ht.signal_id IS 'Referencia ao sinal medido.';
COMMENT ON COLUMN openplot.measurements_ht.value IS 'Valor numerico da amostra.';

CREATE TABLE IF NOT EXISTS openplot.measurements_raw (
    ts          timestamp with time zone NOT NULL,
    pdc_pmu_id  integer NOT NULL,
    point_id    bigint NOT NULL,
    value       double precision NOT NULL,

    CONSTRAINT measurements_raw_pkey PRIMARY KEY (pdc_pmu_id, point_id, ts),
    CONSTRAINT measurements_raw_pdc_pmu_id_fkey
        FOREIGN KEY (pdc_pmu_id)
        REFERENCES openplot.pdc_pmu (pdc_pmu_id)
        ON DELETE CASCADE
);

-- View de compatibilidade para codigo legado que ainda consulta openplot.measurements.
-- Em instalacoes novas, consultas SELECT em measurements passam a ler measurements_ht.
CREATE OR REPLACE VIEW openplot.measurements AS
SELECT
    ts,
    pdc_pmu_id,
    signal_id,
    value
FROM openplot.measurements_ht;

COMMENT ON VIEW openplot.measurements IS
'View de compatibilidade: substitui a tabela legada measurements e aponta para measurements_ht.';

-- -----------------------------------------------------------------------------
-- Logs da API
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS openplot.api_request_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    timestamp_utc   timestamp(6) with time zone NOT NULL,
    method          character varying(10) NOT NULL,
    path            character varying(512) NOT NULL,
    status_code     integer NOT NULL,
    elapsed_ms      integer NOT NULL,
    username        character varying(255),
    user_id         character varying(255),
    ip              character varying(45),
    correlation_id  character varying(64),
    user_agent      text,
    protocol        character varying(16),
    content_type    text,
    content_length  bigint,
    request_body    text,
    query_string    text,

    CONSTRAINT api_request_log_pkey PRIMARY KEY (id),
    CONSTRAINT api_request_log_status_code_check CHECK (status_code >= 100 AND status_code <= 599),
    CONSTRAINT api_request_log_elapsed_ms_check CHECK (elapsed_ms >= 0),
    CONSTRAINT api_request_log_content_length_check CHECK (content_length IS NULL OR content_length >= 0)
);

-- -----------------------------------------------------------------------------
-- SSO
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS openplot.sso_request_nonce (
    id          uuid NOT NULL,
    client_id   character varying(100) NOT NULL,
    nonce       character varying(200) NOT NULL,
    created_at  timestamp with time zone NOT NULL,
    expires_at  timestamp with time zone NOT NULL,

    CONSTRAINT sso_request_nonce_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS openplot.sso_login_token (
    id             uuid NOT NULL,
    token          character varying(500) NOT NULL,
    consulta_id    character varying(100) NOT NULL,
    origin_client  character varying(100) NOT NULL,
    created_at     timestamp with time zone NOT NULL,
    expires_at     timestamp with time zone NOT NULL,
    used           boolean NOT NULL DEFAULT false,
    used_at        timestamp with time zone,

    CONSTRAINT sso_login_token_pkey PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- Funcao de limpeza do cache
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION openplot.clean_expired_analysis_cache()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM openplot.analysis_cache
    WHERE last_accessed_at < now() - INTERVAL '24 hours';
END;
$$;

-- -----------------------------------------------------------------------------
-- Indices
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS ix_api_request_log_correlation_id
ON openplot.api_request_log USING btree (correlation_id);

CREATE INDEX IF NOT EXISTS ix_api_request_log_path
ON openplot.api_request_log USING btree (path);

CREATE INDEX IF NOT EXISTS ix_api_request_log_timestamp_utc
ON openplot.api_request_log USING btree (timestamp_utc);

CREATE INDEX IF NOT EXISTS ix_api_request_log_username
ON openplot.api_request_log USING btree (username);

CREATE INDEX IF NOT EXISTS ix_analysis_cache_job_id
ON openplot.analysis_cache USING btree (job_id);

CREATE INDEX IF NOT EXISTS ix_analysis_cache_last_accessed_at
ON openplot.analysis_cache USING btree (last_accessed_at);

CREATE INDEX IF NOT EXISTS ix_signal_historian_point
ON openplot.signal USING btree (historian_point);

CREATE INDEX IF NOT EXISTS ix_signal_pdc_pmu_id
ON openplot.signal USING btree (pdc_pmu_id);

CREATE INDEX IF NOT EXISTS ix_signal_points_pdc_point
ON openplot.signal_points USING btree (pdc_id, point_id);

CREATE INDEX IF NOT EXISTS ix_search_runs_status_created_at
ON openplot.search_runs USING btree (status, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_search_runs_username_created_at
ON openplot.search_runs USING btree (username, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_search_runs_pdc_id_created_at
ON openplot.search_runs USING btree (pdc_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_comtrade_runs_created_by_created_at
ON openplot.comtrade_runs USING btree (created_by, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_comtrade_runs_status
ON openplot.comtrade_runs USING btree (status);

CREATE INDEX IF NOT EXISTS ix_ingest_chunks_job_id
ON openplot.ingest_chunks USING btree (job_id);

CREATE INDEX IF NOT EXISTS ix_ingest_chunks_signal_id_from_ts
ON openplot.ingest_chunks USING btree (signal_id, from_ts);

-- Indices especificos da hypertable.
-- A PK ja cobre (pdc_pmu_id, signal_id, ts). Os indices abaixo atendem consultas
-- amplas por tempo e consultas por sinal.
CREATE INDEX IF NOT EXISTS ix_measurements_ht_ts
ON openplot.measurements_ht USING btree (ts DESC);

CREATE INDEX IF NOT EXISTS ix_measurements_ht_signal_ts
ON openplot.measurements_ht USING btree (signal_id, ts DESC);

CREATE INDEX IF NOT EXISTS ix_measurements_ht_pdc_pmu_ts
ON openplot.measurements_ht USING btree (pdc_pmu_id, ts DESC);

CREATE INDEX IF NOT EXISTS ix_measurements_raw_ts
ON openplot.measurements_raw USING btree (ts);

CREATE INDEX IF NOT EXISTS ix_measurements_raw_point_ts
ON openplot.measurements_raw USING btree (point_id, ts);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sso_request_nonce_client_nonce
ON openplot.sso_request_nonce USING btree (client_id, nonce);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sso_login_token_token
ON openplot.sso_login_token USING btree (token);

-- -----------------------------------------------------------------------------
-- Compressao TimescaleDB
-- -----------------------------------------------------------------------------
--
ALTER TABLE openplot.measurements_ht SET (
     timescaledb.compress,
     timescaledb.compress_segmentby = 'pdc_pmu_id, signal_id',
     timescaledb.compress_orderby = 'ts DESC'
 );
--
SELECT add_compression_policy(
     'openplot.measurements_ht',
     INTERVAL '7 days',
     if_not_exists => TRUE
 );

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

GRANT SELECT ON TABLE openplot.api_request_log TO grafana;
GRANT SELECT ON TABLE openplot.pdc TO grafana;
GRANT SELECT ON TABLE openplot.pmu TO grafana;
GRANT SELECT ON TABLE openplot.pdc_pmu TO grafana;
GRANT SELECT ON TABLE openplot.signal TO grafana;
GRANT SELECT ON TABLE openplot.signal_points TO grafana;
GRANT SELECT ON TABLE openplot.search_runs TO grafana;
GRANT SELECT ON TABLE openplot.comtrade_runs TO grafana;
GRANT SELECT ON TABLE openplot.analysis_cache TO grafana;
GRANT SELECT ON TABLE openplot.ingest_chunks TO grafana;
GRANT SELECT ON TABLE openplot.measurements TO grafana;
GRANT SELECT ON TABLE openplot.measurements_ht TO grafana;
GRANT SELECT ON TABLE openplot.measurements_raw TO grafana;

ALTER DEFAULT PRIVILEGES IN SCHEMA openplot
GRANT SELECT ON TABLES TO grafana;
